name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library-swift-latest:
    name: Library
    runs-on: macos-14
    strategy:
      matrix:
        config:
          - debug
          - release
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app
      - name: Build ${{ matrix.config }}
        run: make CONFIG=${{ matrix.config }} build-all-platforms
      - name: Run ${{ matrix.config }} tests
        run: make CONFIG=${{ matrix.config }} test-library
